subtitle: Intelligent Systems II
author: MÃ¡rio Antunes
institute: Universidade de Aveiro

fontsize: 12pt
linestretch: 1.25
geometry: "a4paper, margin=2.5cm"

mainfont: "Noto Serif"
sansfont: "Noto Sans"
monofont: "Noto Sans Mono"

colorlinks: true
urlcolor: "blue"
linkcolor: "black"
highlight-style: tango

header-includes:
  - \usepackage{parskip}
  - \usepackage{fancyhdr}
  - \pagestyle{fancy}
  - \fancyhead[L]{\leftmark}
  - \fancyhead[R]{\thepage}
  - \fancyfoot{}
  - \usepackage{longtable,booktabs}
  - \usepackage{etoolbox}
  - \AtBeginEnvironment{longtable}{\normalsize}
  - \AtBeginEnvironment{verbatim}{\normalsize}
