subtitle: Intelligent Systems II
author: MÃ¡rio Antunes
institute: Universidade de Aveiro
colorlinks: true
highlight-style: tango
mainfont: Noto Sans
sansfont: Noto Sans
monofont: Noto Sans Mono
theme: metropolis
themeoptions:
  - sectionpage=progressbar
  - numbering=fraction
  - progressbar=frametitle
header-includes:
 - \usepackage{booktabs}
 - \usepackage{etoolbox}